import Head from "next/head";
import Navbar from "../components/Layout/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pratik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-dark text-light font-raleway">
        <Navbar></Navbar>
      </div>
    </div>
  );
}
