import Head from "next/head";
import Hero from "../components/Layout/Hero";
import Navbar from "../components/Layout/Navbar";
import Footer from "../components/Layout/Footer";
import Projects from "../components/Projects";

export default function Home() {
  1;
  return (
    <div>
      <Head>
        <title>Pratik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gblack">
        <div className="bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))]   from-g700 via-g900 to-gblack font-raleway text-light">
          <Navbar />
          <div className="mx-auto  max-w-[660px] lg:max-w-[900px]   xl:max-w-[1100px]">
            <Hero />
            <Projects />
          </div>
        </div>
        <div className="mx-auto  max-w-[660px] lg:max-w-[900px]   xl:max-w-[1100px]">
          <Footer />
        </div>
        <div className="flex justify-center text-xl text-light border-t-g700 border-t-2">
         <p className="py-3">
         Made with ❤️ by <a href="https://www.pratikdevdas.com" className="underline pl-1 text-green hover:text-light"> Pratik.</a> Read my blogs <a href="https://blog.pratikdevdas.com/" className="underline pl-1 text-green hover:text-light" >here.</a></p> 
        </div>
      </div>
    </div>
  );
}
